version: '3.1'

services:
  db:
    image: mysql/mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: oEl10vpeXUVg
      MYSQL_DATABASE: music
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuser
    ports:
      - 3306:3306